# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ipv4', models.GenericIPAddressField(default='10.0.0.2', protocol='IPv4')),
                ('last_ipv4', models.GenericIPAddressField(default='10.0.0.253', protocol='IPv4')),
                ('first_ipv6', models.GenericIPAddressField(default='fd00:db8::3', protocol='IPv6')),
                ('last_ipv6', models.GenericIPAddressField(default='fd00:db8::ffff', protocol='IPv6')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
