# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnadm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='crt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ca_crt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ca_key',
            field=models.TextField(blank=True),
        ),
    ]
