# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnadm', '0002_auto_20181214_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='serial',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
