# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnadm', '0003_client_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='dh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ta_key',
            field=models.TextField(blank=True),
        ),
    ]
