# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnadm', '0004_auto_20181217_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='ipv4_netmask',
            field=models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ipv6_prefix',
            field=models.IntegerField(default=64),
        ),
    ]
