# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpnadm', '0005_auto_20181217_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('netmask', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.GenericIPAddressField(protocol='IPv6', unique=True)),
                ('prefix', models.IntegerField(default=64)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='first_ipv4',
            field=models.GenericIPAddressField(default='10.0.0.2', protocol='IPv4', verbose_name='First Client IPv4 Address'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='first_ipv6',
            field=models.GenericIPAddressField(default='fd00:db8::3', protocol='IPv6', verbose_name='First Client IPv6 Address'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='ipv4_netmask',
            field=models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4', verbose_name='IPv4 Client Netmask'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='ipv6_prefix',
            field=models.IntegerField(default=64, verbose_name='IPv6 Client Prefixlength'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='last_ipv4',
            field=models.GenericIPAddressField(default='10.0.0.253', protocol='IPv4', verbose_name='Last Client IPv4 Address'),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='last_ipv6',
            field=models.GenericIPAddressField(default='fd00:db8::ffff', protocol='IPv6', verbose_name='Last Client IPv6 Address'),
        ),
    ]
