# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpnadm', '0007_auto_20181217_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route4',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpnadm.Client'),
        ),
        migrations.AlterField(
            model_name='route6',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpnadm.Client'),
        ),
    ]
